const $=id=>document.getElementById(id);
const bootLines=["ASH VECTOR OPERATING SYSTEM","Version 0.0.1 // Developer Build 1.0","","Initializing...","Connecting to ASH Network...","Connection Established.","Loading Classified Archives...","Operator Database... ONLINE","Anomaly Database... ONLINE","Fracture Index... ONLINE","Reality Integrity... ERROR","Reality Integrity: 18%","","WARNING","Unauthorized access detected.","","Can you hear me...?"];
let bootI=0;function boot(){const lines=$('bootLines'),bar=$('bootProgress').firstElementChild;if(bootI<bootLines.length){lines.textContent+=bootLines[bootI]+"\n";bar.style.width=Math.min(100,bootI/bootLines.length*100)+'%';bootI++;setTimeout(boot,bootLines[bootI-1]===''?180:330)}else{$('bootLogo').classList.remove('hidden');bar.style.width='100%'}};boot();
$('enterBtn').onclick=()=>{$('bootScreen').classList.add('hidden');$('mainMenu').classList.remove('hidden')};
['continueBtn','newGameBtn'].forEach(id=>$(id).onclick=()=>startGame());$('operatorFilesBtn').onclick=()=>$('operatorOverlay').classList.remove('hidden');$('anomalyIndexBtn').onclick=()=>{renderAnomalyDb();$('anomalyOverlay').classList.remove('hidden')};$('fractureIndexBtn').onclick=()=>$('fractureOverlay').classList.remove('hidden');$('inventoryDbBtn').onclick=()=>{renderInvDb();$('inventoryOverlay').classList.remove('hidden')};$('configBtn').onclick=()=>$('menuInfo').textContent='Configuration protocol placeholder. Audio & atmosphere controls arrive next.';
['closeOperatorDb','closeAnomalyDb','closeFractureDb','closeInventoryDb'].forEach(id=>$(id).onclick=()=>$(id).closest('.overlay').classList.add('hidden'));
const canvas=$('game'),ctx=canvas.getContext('2d');
const tile=42;const map=["########################","#P....C.......E.......X#","#..####..####....####..#","#......S....#....#.....#","#..E.......H#....#..C..#","#.......#####....#.....#","#..####.........E..##..#","#......C....####......B#","########################"];
const state={x:1,y:1,hp:120,maxHp:120,level:1,xp:0,credits:0,inventory:{'med_patch':1},log:['AVOS online. Welcome to the bad idea.'],inBattle:false};
const enemies={E:{name:'Rust Hound',hp:80,maxHp:80,img:'assets/anomalies/rust_hound/battle.png'},B:{name:'Rust Mother',hp:160,maxHp:160,img:'assets/anomalies/scrap_crawler/battle.png'}};
function startGame(){$('mainMenu').classList.add('hidden');$('app').classList.remove('hidden');canvas.focus();renderAll()}
function draw(){ctx.fillStyle='#07110d';ctx.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<map.length;y++){for(let x=0;x<map[y].length;x++){const ch=map[y][x];ctx.fillStyle= ch=='#'?'#1e2523':'#111713';ctx.fillRect(x*tile,y*tile,tile-2,tile-2);if(ch=='#'){ctx.fillStyle='#323b36';ctx.fillRect(x*tile+5,y*tile+5,tile-12,tile-12)} if('CESHBX'.includes(ch)){ctx.fillStyle={C:'#d69b2d',E:'#ff3a2d',S:'#00e0ff',H:'#75ff6a',B:'#b10f0f',X:'#fff'}[ch];ctx.fillRect(x*tile+10,y*tile+10,22,22);ctx.fillStyle='#000';ctx.fillText(ch,x*tile+17,y*tile+27)}}}ctx.fillStyle='#ff2a2a';ctx.beginPath();ctx.arc(state.x*tile+21,state.y*tile+21,16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText('V',state.x*tile+16,state.y*tile+26)}
function move(dx,dy){if(state.inBattle)return;let nx=state.x+dx,ny=state.y+dy,ch=map[ny]?.[nx];if(!ch||ch=='#')return;state.x=nx;state.y=ny;if(ch=='C'){addLog('Cache opened: +25 credits, Scrap Metal x1. The box was richer than you.');state.credits+=25;state.inventory.scrap_metal=(state.inventory.scrap_metal||0)+1}if(ch=='S')save();if(ch=='H'){state.hp=state.maxHp;addLog('Recovery station healed Vyra. It also judged her life choices.')}if(ch=='E'||ch=='B')startBattle(ch);if(ch=='X')addLog('Exit detected. Next Fracture not yet authorized.');renderAll()}
function renderAll(){draw();$('stats').innerHTML=`LV ${state.level}<br>HP ${state.hp}/${state.maxHp}<div class=bar><span style="width:${state.hp/state.maxHp*100}%"></span></div>XP ${state.xp}/100<br>Credits ${state.credits}`;$('inventory').innerHTML=Object.entries(state.inventory).map(([k,v])=>`${k.replaceAll('_',' ')} x${v}`).join('<br>')||'Empty';$('roster').innerHTML='AV-001 Vyra // ACTIVE';$('log').innerHTML=state.log.slice(-8).map(x=>'› '+x).join('<br>');$('fractureStatus').innerHTML=`F-001 Toxic Sewers<br>Position ${state.x},${state.y}<br>Reality Integrity 81%`;$('operatorSync').textContent=Math.min(100,state.xp)+'%'}
function addLog(t){state.log.push(t)}
window.addEventListener('keydown',e=>{if(e.key==='ArrowUp')move(0,-1);if(e.key==='ArrowDown')move(0,1);if(e.key==='ArrowLeft')move(-1,0);if(e.key==='ArrowRight')move(1,0);if(e.key==='Enter'&&!$('bootScreen').classList.contains('hidden')&&!$('bootLogo').classList.contains('hidden'))$('enterBtn').click()});document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[b.dataset.move]&&move(...({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[b.dataset.move]));
let foe=null;function startBattle(ch){state.inBattle=true;foe={...enemies[ch]};$('battleTitle').textContent=foe.name;$('battleEnemy').src=foe.img;$('battleOverlay').classList.remove('hidden');renderBattle('Choose a combat protocol.')}function renderBattle(txt){$('battleText').textContent=txt;$('battleHp').innerHTML=`${foe.name} HP ${foe.hp}/${foe.maxHp}<div class=bar><span style="width:${Math.max(0,foe.hp)/foe.maxHp*100}%"></span></div>Vyra HP ${state.hp}/${state.maxHp}<div class=bar><span style="width:${state.hp/state.maxHp*100}%"></span></div>`;const attacks=[['Neon Slash',28],['Trash Talk',16],['Void Kick',36],['Emergency Flex',20]];$('attackButtons').innerHTML='';attacks.forEach(a=>{let b=document.createElement('button');b.textContent=`${a[0]} // ${a[1]} DMG`;b.onclick=()=>attack(a[0],a[1]);$('attackButtons').appendChild(b)})}
function attack(name,dmg){let crit=Math.random()<.18;let total=dmg+(crit?18:0);foe.hp-=total;if(foe.hp<=0){state.inBattle=false;$('battleOverlay').classList.add('hidden');state.xp+=45;state.credits+=40;state.inventory.rust_core=(state.inventory.rust_core||0)+1;if(state.xp>=100){state.level++;state.xp-=100;state.maxHp+=15;state.hp=state.maxHp;addLog('Synchronization increased. Vyra got stronger and somehow more smug.')}addLog(`${foe.name} neutralized. Loot recovered: Rust Core, 40 credits.`);renderAll();return}let hit=Math.random()<.85;if(hit){let edmg=12+Math.floor(Math.random()*10);state.hp=Math.max(1,state.hp-edmg);renderBattle(`${name} hit for ${total}${crit?' CRITICAL':''}. ${foe.name} bit back for ${edmg}.`)}else renderBattle(`${name} hit for ${total}. ${foe.name} missed. Embarrassing.`);renderAll()}
function save(){localStorage.setItem('ashVectorSave',JSON.stringify(state));addLog('VECTOR ARCHIVE updated.');renderAll()}function load(){let s=localStorage.getItem('ashVectorSave');if(s){Object.assign(state,JSON.parse(s));addLog('VECTOR ARCHIVE loaded.');renderAll()}}$('saveBtn').onclick=save;$('loadBtn').onclick=load;$('menuBtn').onclick=()=>{$('app').classList.add('hidden');$('mainMenu').classList.remove('hidden')};$('resetBtn').onclick=()=>{localStorage.removeItem('ashVectorSave');location.reload()};
function renderAnomalyDb(){const list=$('anomalyList'),file=$('anomalyFile');list.innerHTML='';[['Rust Hound','Low threat scrap-beast.'],['Toxic Slime','Semi-liquid regret.'],['Scrap Crawler','Mechanical ankle crime.']].forEach((a,i)=>{let b=document.createElement('button');b.className='anomaly-btn';b.textContent=a[0];b.onclick=()=>file.innerHTML=`<div class=record-kicker>ANOMALY FILE 00${i+1}</div><h2>${a[0]}</h2><p>${a[1]}</p><div class=record-grid><div><b>Threat</b><span>${i?'Medium':'Low'}</span></div><div><b>Loot</b><span>Scrap / Core</span></div></div>`;list.appendChild(b)})}
function renderInvDb(){$('inventoryDatabaseList').innerHTML=Object.entries(state.inventory).map(([k,v])=>`<div class=protocol-list><div><b>${k.replaceAll('_',' ').toUpperCase()}</b><span>Quantity: ${v}</span></div></div>`).join('')||'No recovered assets.'}
